name: margohan_env
channels:
  - defaults
dependencies:
  - python=3.10
  - scikit-learn
  - pandas
  - numpy
  - pip
  - pip:
      - mlflow==2.19.0
      - joblib
      - cloudpickle
      - pyyaml
      - sqlalchemy
