name: margohan_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.19.0
      - scikit-learn
      - pandas
      - numpy
      - joblib
      - cloudpickle
      - pyyaml
      - sqlalchemy
