# MLProject/conda.yaml
name: margohan_env
channels:
  - defaults
  - conda-forge 
dependencies:
  - python=3.10
  - mlflow=2.19.0
  # Dependensi utama
  - scikit-learn=1.2.2 
  - pandas=2.2.0
  - numpy
  - joblib
  - cloudpickle
  - pyyaml
  - sqlalchemy